Рюмина Кира 09.07.14п2 ПР4

Импортируем библиотеки

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Загружаем датасет

In [2]:
df = pd.read_csv("titanic.csv")

Выводим первые 5 строк таблицы

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Определяем целевую переменную

In [4]:
y = df["Survived"]

In [5]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

Возьмем признаки: Pclass, Age, Sex, Fare, SibSp, Parch

In [7]:
X = df[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch"]]

In [8]:
X.head()

   Pclass   Age     Sex     Fare  SibSp  Parch
0       3  22.0    male   7.2500      1      0
1       1  38.0  female  71.2833      1      0
2       3  26.0  female   7.9250      0      0
3       1  35.0  female  53.1000      1      0
4       3  35.0    male   8.0500      0      0

Узнаем количество пропусков в признаках

In [9]:
X.isnull().sum()

Pclass      0
Age       177
Sex         0
Fare        0
SibSp       0
Parch       0
dtype: int64

Заполним пропущенные значения в возрасте медианой

In [11]:
X["Age"] = X["Age"].fillna(X["Age"].median())

/tmp/ipykernel_2667/2770350965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Age"] = X["Age"].fillna(X["Age"].median())

In [12]:
X.isnull().sum()

Pclass    0
Age       0
Sex       0
Fare      0
SibSp     0
Parch     0
dtype: int64

Преобразуем категориальные значения в числовые, преобразуем пол в числовой вид

In [13]:
X["Sex"] = X["Sex"].map({
    "male": 0,
    "female": 1
})

/tmp/ipykernel_2667/3323189253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex"] = X["Sex"].map({

In [14]:
X.head()

   Pclass   Age  Sex     Fare  SibSp  Parch
0       3  22.0    0   7.2500      1      0
1       1  38.0    1  71.2833      1      0
2       3  26.0    1   7.9250      0      0
3       1  35.0    1  53.1000      1      0
4       3  35.0    0   8.0500      0      0

Проверим подготовленные данные

In [15]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Age     891 non-null    float64
 2   Sex     891 non-null    int64
 3   Fare    891 non-null    float64
 4   SibSp   891 non-null    int64
 5   Parch   891 non-null    int64
dtypes: float64(2), int64(4)
memory usage: 41.9 KB

Проверим пропуски на всякий случай

In [16]:
X.isnull().sum()

Pclass    0
Age       0
Sex       0
Fare      0
SibSp     0
Parch     0
dtype: int64

Разделяем данные на обучающую и тестовую выборку

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Проверяем размеры выборок

In [19]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (712, 6)
X_test: (179, 6)
y_train: (712,)
y_test: (179,)

Масштабируем признаки

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Итоговые размеры полученных наборов данных

In [23]:
print("X_train_scaled.shape: ", X_train_scaled.shape)
print("X_test_scaled.shape: ", X_test_scaled.shape)
print("y_train.shape: ", y_train.shape)
print("y_test.shape: ", y_test.shape)

X_train_scaled.shape:  (712, 6)
X_test_scaled.shape:  (179, 6)
y_train.shape:  (712,)
y_test.shape:  (179,)